repository:
  type: InMemory
notifications:
  - type: slack
    receivers:
      - channel-name
event_bus:
  type: InMemory
  observers_by_event:
    - event_name: book_created
      observers:
        - NewBookLogger